[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ".git"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
ruff = { enabled = true, lineLength = 100, format = ["I"] }

[language-server.rust-analyzer]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]

[language-server.rust-analyzer.config]
Check = { command = "clippy" }

[language-server.ltex-ls.config]
ltex.disabledRules = {  "en-US" = [ "PROFANITY" ], "en-GB" = [ "PROFANITY" ] }
ltex.dictionary = { "en-US" = [ "builtin" ], "en-GB" = [ "builtin" ] }

[[language]]
name = "go"
formatter = { command = "golines", args = ["-m", "120"]}

[language-server.gopls.config]
gofumpt = true
local = "gitlab.figo.systems"

[[language]]
name = "yaml"
file-types = ["yml", "yaml", "argo-yaml"]

[[language]]
name = "html"
formatter = { command = "npx prettier", args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = "npx prettier", args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = "npx prettier", args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = "npx prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "npx prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "xml"
formatter = { command = "npx prettier", args = ["--parser", "xml"]}

[[language]]
name = "markdown"
language-servers = [ "ltex-ls" ]

[[language]]
name = "hcl"
formatter = { command = "terraform", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

