" Plug 'godlygeek/csapprox'
Plug 'chrisbra/colorizer'
Plug 'itchyny/lightline.vim'
Plug 'skwp/vim-colors-solarized'
Plug 'romainl/flattened'
Plug 'junegunn/seoul256.vim'
Plug 'romainl/Apprentice'
Plug 'morhetz/gruvbox'
Plug 'whatyouhide/vim-gotham'
Plug 'jeetsukumaran/vim-markology'
Plug 'chriskempson/base16-vim'
