"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 700

format = "$character"
right_format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$python\
$kubernetes"""

[character]
success_symbol = "[λ](blue)"
error_symbol = "[λ](red)"
vimcmd_symbol = "❯"

[git_branch]
format = '[$branch]($style)'
style = "bold white"

[git_status]
format = ":[$all_status$ahead_behind]($style)"
style = "bold purple"

[python]
format = ' [$virtualenv]($style)@$version'
version_format = "$major.$minor"

[kubernetes]
disabled = false
format = " [$context](red bold):[$namespace](cyan bold)"

[[kubernetes.contexts]]
context_pattern = 'fcloud-(?P<cluster>\w*-\w*-\w*)-.*'
context_alias = "$cluster"
