"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "$character"
right_format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$python\
$kubernetes"""

[character]
success_symbol = "[λ](blue)"
error_symbol = "[λ](red)"
vimcmd_symbol = "❯"

[git_branch]
format = '[$branch]($style)'
style = "bold white"

[git_status]
format = ":[$all_status$ahead_behind]($style)"
style = "bold purple"

[python]
format = ' [$virtualenv]($style) '

[kubernetes]
format = "[$context](red bold):[$namespace](cyan bold)"
disabled = false

[kubernetes.context_aliases]
'fcloud-(?P<cluster>\w*-\w*-\w*)-.*' = '$cluster'